/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedVouchersIndexRouteImport } from './routes/_authenticated/vouchers/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTechniciansIndexRouteImport } from './routes/_authenticated/technicians/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers/index'
import { Route as AuthenticatedRoutersIndexRouteImport } from './routes/_authenticated/routers/index'
import { Route as AuthenticatedProfilesIndexRouteImport } from './routes/_authenticated/profiles/index'
import { Route as AuthenticatedPosTransactionsIndexRouteImport } from './routes/_authenticated/pos-transactions/index'
import { Route as AuthenticatedPlansIndexRouteImport } from './routes/_authenticated/plans/index'
import { Route as AuthenticatedMonitoringIndexRouteImport } from './routes/_authenticated/monitoring/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedActivityIndexRouteImport } from './routes/_authenticated/activity/index'
import { Route as AuthenticatedActiveUsersIndexRouteImport } from './routes/_authenticated/active-users/index'
import { Route as AuthenticatedVouchersAddSingleRouteImport } from './routes/_authenticated/vouchers/add-single'
import { Route as AuthenticatedVouchersAddBulkRouteImport } from './routes/_authenticated/vouchers/add-bulk'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users/$id'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedServersAddRouteImport } from './routes/_authenticated/servers/add'
import { Route as AuthenticatedRoutersIdRouteImport } from './routes/_authenticated/routers/$id'
import { Route as AuthenticatedProfilesAddRouteImport } from './routes/_authenticated/profiles/add'
import { Route as AuthenticatedPlansAddRouteImport } from './routes/_authenticated/plans/add'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDeveloperKeysIndexRouteImport } from './routes/_authenticated/developer/keys/index'
import { Route as AuthenticatedDeveloperDocsIndexRouteImport } from './routes/_authenticated/developer/docs/index'
import { Route as AuthenticatedServersEditIdRouteImport } from './routes/_authenticated/servers/edit.$id'
import { Route as AuthenticatedPlansEditIdRouteImport } from './routes/_authenticated/plans/edit.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVouchersIndexRoute =
  AuthenticatedVouchersIndexRouteImport.update({
    id: '/vouchers/',
    path: '/vouchers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTechniciansIndexRoute =
  AuthenticatedTechniciansIndexRouteImport.update({
    id: '/technicians/',
    path: '/technicians/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoutersIndexRoute =
  AuthenticatedRoutersIndexRouteImport.update({
    id: '/routers/',
    path: '/routers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilesIndexRoute =
  AuthenticatedProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosTransactionsIndexRoute =
  AuthenticatedPosTransactionsIndexRouteImport.update({
    id: '/pos-transactions/',
    path: '/pos-transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansIndexRoute = AuthenticatedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringIndexRoute =
  AuthenticatedMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityIndexRoute =
  AuthenticatedActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActiveUsersIndexRoute =
  AuthenticatedActiveUsersIndexRouteImport.update({
    id: '/active-users/',
    path: '/active-users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVouchersAddSingleRoute =
  AuthenticatedVouchersAddSingleRouteImport.update({
    id: '/vouchers/add-single',
    path: '/vouchers/add-single',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVouchersAddBulkRoute =
  AuthenticatedVouchersAddBulkRouteImport.update({
    id: '/vouchers/add-bulk',
    path: '/vouchers/add-bulk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServersAddRoute = AuthenticatedServersAddRouteImport.update({
  id: '/servers/add',
  path: '/servers/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutersIdRoute = AuthenticatedRoutersIdRouteImport.update({
  id: '/routers/$id',
  path: '/routers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilesAddRoute =
  AuthenticatedProfilesAddRouteImport.update({
    id: '/profiles/add',
    path: '/profiles/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansAddRoute = AuthenticatedPlansAddRouteImport.update({
  id: '/plans/add',
  path: '/plans/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperKeysIndexRoute =
  AuthenticatedDeveloperKeysIndexRouteImport.update({
    id: '/developer/keys/',
    path: '/developer/keys/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperDocsIndexRoute =
  AuthenticatedDeveloperDocsIndexRouteImport.update({
    id: '/developer/docs/',
    path: '/developer/docs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServersEditIdRoute =
  AuthenticatedServersEditIdRouteImport.update({
    id: '/servers/edit/$id',
    path: '/servers/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansEditIdRoute =
  AuthenticatedPlansEditIdRouteImport.update({
    id: '/plans/edit/$id',
    path: '/plans/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/plans/add': typeof AuthenticatedPlansAddRoute
  '/profiles/add': typeof AuthenticatedProfilesAddRoute
  '/routers/$id': typeof AuthenticatedRoutersIdRoute
  '/servers/add': typeof AuthenticatedServersAddRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/vouchers/add-bulk': typeof AuthenticatedVouchersAddBulkRoute
  '/vouchers/add-single': typeof AuthenticatedVouchersAddSingleRoute
  '/active-users/': typeof AuthenticatedActiveUsersIndexRoute
  '/activity/': typeof AuthenticatedActivityIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/plans/': typeof AuthenticatedPlansIndexRoute
  '/pos-transactions/': typeof AuthenticatedPosTransactionsIndexRoute
  '/profiles/': typeof AuthenticatedProfilesIndexRoute
  '/routers/': typeof AuthenticatedRoutersIndexRoute
  '/servers/': typeof AuthenticatedServersIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/technicians/': typeof AuthenticatedTechniciansIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/vouchers/': typeof AuthenticatedVouchersIndexRoute
  '/plans/edit/$id': typeof AuthenticatedPlansEditIdRoute
  '/servers/edit/$id': typeof AuthenticatedServersEditIdRoute
  '/developer/docs/': typeof AuthenticatedDeveloperDocsIndexRoute
  '/developer/keys/': typeof AuthenticatedDeveloperKeysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/plans/add': typeof AuthenticatedPlansAddRoute
  '/profiles/add': typeof AuthenticatedProfilesAddRoute
  '/routers/$id': typeof AuthenticatedRoutersIdRoute
  '/servers/add': typeof AuthenticatedServersAddRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/vouchers/add-bulk': typeof AuthenticatedVouchersAddBulkRoute
  '/vouchers/add-single': typeof AuthenticatedVouchersAddSingleRoute
  '/active-users': typeof AuthenticatedActiveUsersIndexRoute
  '/activity': typeof AuthenticatedActivityIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/plans': typeof AuthenticatedPlansIndexRoute
  '/pos-transactions': typeof AuthenticatedPosTransactionsIndexRoute
  '/profiles': typeof AuthenticatedProfilesIndexRoute
  '/routers': typeof AuthenticatedRoutersIndexRoute
  '/servers': typeof AuthenticatedServersIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/technicians': typeof AuthenticatedTechniciansIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vouchers': typeof AuthenticatedVouchersIndexRoute
  '/plans/edit/$id': typeof AuthenticatedPlansEditIdRoute
  '/servers/edit/$id': typeof AuthenticatedServersEditIdRoute
  '/developer/docs': typeof AuthenticatedDeveloperDocsIndexRoute
  '/developer/keys': typeof AuthenticatedDeveloperKeysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/plans/add': typeof AuthenticatedPlansAddRoute
  '/_authenticated/profiles/add': typeof AuthenticatedProfilesAddRoute
  '/_authenticated/routers/$id': typeof AuthenticatedRoutersIdRoute
  '/_authenticated/servers/add': typeof AuthenticatedServersAddRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute
  '/_authenticated/vouchers/add-bulk': typeof AuthenticatedVouchersAddBulkRoute
  '/_authenticated/vouchers/add-single': typeof AuthenticatedVouchersAddSingleRoute
  '/_authenticated/active-users/': typeof AuthenticatedActiveUsersIndexRoute
  '/_authenticated/activity/': typeof AuthenticatedActivityIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/_authenticated/plans/': typeof AuthenticatedPlansIndexRoute
  '/_authenticated/pos-transactions/': typeof AuthenticatedPosTransactionsIndexRoute
  '/_authenticated/profiles/': typeof AuthenticatedProfilesIndexRoute
  '/_authenticated/routers/': typeof AuthenticatedRoutersIndexRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/technicians/': typeof AuthenticatedTechniciansIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/vouchers/': typeof AuthenticatedVouchersIndexRoute
  '/_authenticated/plans/edit/$id': typeof AuthenticatedPlansEditIdRoute
  '/_authenticated/servers/edit/$id': typeof AuthenticatedServersEditIdRoute
  '/_authenticated/developer/docs/': typeof AuthenticatedDeveloperDocsIndexRoute
  '/_authenticated/developer/keys/': typeof AuthenticatedDeveloperKeysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/errors/$error'
    | '/plans/add'
    | '/profiles/add'
    | '/routers/$id'
    | '/servers/add'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/users/$id'
    | '/vouchers/add-bulk'
    | '/vouchers/add-single'
    | '/active-users/'
    | '/activity/'
    | '/apps/'
    | '/billing/'
    | '/chats/'
    | '/help-center/'
    | '/monitoring/'
    | '/plans/'
    | '/pos-transactions/'
    | '/profiles/'
    | '/routers/'
    | '/servers/'
    | '/settings/'
    | '/tasks/'
    | '/technicians/'
    | '/users/'
    | '/vouchers/'
    | '/plans/edit/$id'
    | '/servers/edit/$id'
    | '/developer/docs/'
    | '/developer/keys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/errors/$error'
    | '/plans/add'
    | '/profiles/add'
    | '/routers/$id'
    | '/servers/add'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/users/$id'
    | '/vouchers/add-bulk'
    | '/vouchers/add-single'
    | '/active-users'
    | '/activity'
    | '/apps'
    | '/billing'
    | '/chats'
    | '/help-center'
    | '/monitoring'
    | '/plans'
    | '/pos-transactions'
    | '/profiles'
    | '/routers'
    | '/servers'
    | '/settings'
    | '/tasks'
    | '/technicians'
    | '/users'
    | '/vouchers'
    | '/plans/edit/$id'
    | '/servers/edit/$id'
    | '/developer/docs'
    | '/developer/keys'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dashboard'
    | '/_authenticated/errors/$error'
    | '/_authenticated/plans/add'
    | '/_authenticated/profiles/add'
    | '/_authenticated/routers/$id'
    | '/_authenticated/servers/add'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/users/$id'
    | '/_authenticated/vouchers/add-bulk'
    | '/_authenticated/vouchers/add-single'
    | '/_authenticated/active-users/'
    | '/_authenticated/activity/'
    | '/_authenticated/apps/'
    | '/_authenticated/billing/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/monitoring/'
    | '/_authenticated/plans/'
    | '/_authenticated/pos-transactions/'
    | '/_authenticated/profiles/'
    | '/_authenticated/routers/'
    | '/_authenticated/servers/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/technicians/'
    | '/_authenticated/users/'
    | '/_authenticated/vouchers/'
    | '/_authenticated/plans/edit/$id'
    | '/_authenticated/servers/edit/$id'
    | '/_authenticated/developer/docs/'
    | '/_authenticated/developer/keys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers/': {
      id: '/_authenticated/vouchers/'
      path: '/vouchers'
      fullPath: '/vouchers/'
      preLoaderRoute: typeof AuthenticatedVouchersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technicians/': {
      id: '/_authenticated/technicians/'
      path: '/technicians'
      fullPath: '/technicians/'
      preLoaderRoute: typeof AuthenticatedTechniciansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routers/': {
      id: '/_authenticated/routers/'
      path: '/routers'
      fullPath: '/routers/'
      preLoaderRoute: typeof AuthenticatedRoutersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles/': {
      id: '/_authenticated/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AuthenticatedProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos-transactions/': {
      id: '/_authenticated/pos-transactions/'
      path: '/pos-transactions'
      fullPath: '/pos-transactions/'
      preLoaderRoute: typeof AuthenticatedPosTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/': {
      id: '/_authenticated/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AuthenticatedPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring/': {
      id: '/_authenticated/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof AuthenticatedMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity/': {
      id: '/_authenticated/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthenticatedActivityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/active-users/': {
      id: '/_authenticated/active-users/'
      path: '/active-users'
      fullPath: '/active-users/'
      preLoaderRoute: typeof AuthenticatedActiveUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers/add-single': {
      id: '/_authenticated/vouchers/add-single'
      path: '/vouchers/add-single'
      fullPath: '/vouchers/add-single'
      preLoaderRoute: typeof AuthenticatedVouchersAddSingleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers/add-bulk': {
      id: '/_authenticated/vouchers/add-bulk'
      path: '/vouchers/add-bulk'
      fullPath: '/vouchers/add-bulk'
      preLoaderRoute: typeof AuthenticatedVouchersAddBulkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/servers/add': {
      id: '/_authenticated/servers/add'
      path: '/servers/add'
      fullPath: '/servers/add'
      preLoaderRoute: typeof AuthenticatedServersAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routers/$id': {
      id: '/_authenticated/routers/$id'
      path: '/routers/$id'
      fullPath: '/routers/$id'
      preLoaderRoute: typeof AuthenticatedRoutersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles/add': {
      id: '/_authenticated/profiles/add'
      path: '/profiles/add'
      fullPath: '/profiles/add'
      preLoaderRoute: typeof AuthenticatedProfilesAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/add': {
      id: '/_authenticated/plans/add'
      path: '/plans/add'
      fullPath: '/plans/add'
      preLoaderRoute: typeof AuthenticatedPlansAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/keys/': {
      id: '/_authenticated/developer/keys/'
      path: '/developer/keys'
      fullPath: '/developer/keys/'
      preLoaderRoute: typeof AuthenticatedDeveloperKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/docs/': {
      id: '/_authenticated/developer/docs/'
      path: '/developer/docs'
      fullPath: '/developer/docs/'
      preLoaderRoute: typeof AuthenticatedDeveloperDocsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servers/edit/$id': {
      id: '/_authenticated/servers/edit/$id'
      path: '/servers/edit/$id'
      fullPath: '/servers/edit/$id'
      preLoaderRoute: typeof AuthenticatedServersEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/edit/$id': {
      id: '/_authenticated/plans/edit/$id'
      path: '/plans/edit/$id'
      fullPath: '/plans/edit/$id'
      preLoaderRoute: typeof AuthenticatedPlansEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedPlansAddRoute: typeof AuthenticatedPlansAddRoute
  AuthenticatedProfilesAddRoute: typeof AuthenticatedProfilesAddRoute
  AuthenticatedRoutersIdRoute: typeof AuthenticatedRoutersIdRoute
  AuthenticatedServersAddRoute: typeof AuthenticatedServersAddRoute
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute
  AuthenticatedVouchersAddBulkRoute: typeof AuthenticatedVouchersAddBulkRoute
  AuthenticatedVouchersAddSingleRoute: typeof AuthenticatedVouchersAddSingleRoute
  AuthenticatedActiveUsersIndexRoute: typeof AuthenticatedActiveUsersIndexRoute
  AuthenticatedActivityIndexRoute: typeof AuthenticatedActivityIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedMonitoringIndexRoute: typeof AuthenticatedMonitoringIndexRoute
  AuthenticatedPlansIndexRoute: typeof AuthenticatedPlansIndexRoute
  AuthenticatedPosTransactionsIndexRoute: typeof AuthenticatedPosTransactionsIndexRoute
  AuthenticatedProfilesIndexRoute: typeof AuthenticatedProfilesIndexRoute
  AuthenticatedRoutersIndexRoute: typeof AuthenticatedRoutersIndexRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTechniciansIndexRoute: typeof AuthenticatedTechniciansIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVouchersIndexRoute: typeof AuthenticatedVouchersIndexRoute
  AuthenticatedPlansEditIdRoute: typeof AuthenticatedPlansEditIdRoute
  AuthenticatedServersEditIdRoute: typeof AuthenticatedServersEditIdRoute
  AuthenticatedDeveloperDocsIndexRoute: typeof AuthenticatedDeveloperDocsIndexRoute
  AuthenticatedDeveloperKeysIndexRoute: typeof AuthenticatedDeveloperKeysIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedPlansAddRoute: AuthenticatedPlansAddRoute,
  AuthenticatedProfilesAddRoute: AuthenticatedProfilesAddRoute,
  AuthenticatedRoutersIdRoute: AuthenticatedRoutersIdRoute,
  AuthenticatedServersAddRoute: AuthenticatedServersAddRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
  AuthenticatedVouchersAddBulkRoute: AuthenticatedVouchersAddBulkRoute,
  AuthenticatedVouchersAddSingleRoute: AuthenticatedVouchersAddSingleRoute,
  AuthenticatedActiveUsersIndexRoute: AuthenticatedActiveUsersIndexRoute,
  AuthenticatedActivityIndexRoute: AuthenticatedActivityIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedMonitoringIndexRoute: AuthenticatedMonitoringIndexRoute,
  AuthenticatedPlansIndexRoute: AuthenticatedPlansIndexRoute,
  AuthenticatedPosTransactionsIndexRoute:
    AuthenticatedPosTransactionsIndexRoute,
  AuthenticatedProfilesIndexRoute: AuthenticatedProfilesIndexRoute,
  AuthenticatedRoutersIndexRoute: AuthenticatedRoutersIndexRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTechniciansIndexRoute: AuthenticatedTechniciansIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVouchersIndexRoute: AuthenticatedVouchersIndexRoute,
  AuthenticatedPlansEditIdRoute: AuthenticatedPlansEditIdRoute,
  AuthenticatedServersEditIdRoute: AuthenticatedServersEditIdRoute,
  AuthenticatedDeveloperDocsIndexRoute: AuthenticatedDeveloperDocsIndexRoute,
  AuthenticatedDeveloperKeysIndexRoute: AuthenticatedDeveloperKeysIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
